version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/python:3.8

    environment:
      GCLOUD_PROJECT_ID: cinema-389321  
      GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY
      CLUSTER_NAME: cin
      CLUSTER_ZONE: YOUR_CLUSTER_ZONE

    steps:
      - checkout

      # 安装 gcloud SDK
      - run:
          name: Install gcloud SDK
          command: |
            wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-365.0.0-linux-x86_64.tar.gz
            tar xf google-cloud-sdk-365.0.0-linux-x86_64.tar.gz
            ./google-cloud-sdk/install.sh --quiet
            echo 'export PATH=$PATH:/root/google-cloud-sdk/bin' >> $BASH_ENV
            source $BASH_ENV

            # 添加 gcloud SDK 的路径到 PATH 环境变量
            echo 'export PATH=$PATH:/home/circleci/google-cloud-sdk/bin' >> $HOME/.bashrc

      # 配置 gcloud SDK
      - run:
          name: Configure gcloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $GCLOUD_PROJECT_ID
            gcloud container clusters create $CLUSTER_NAME --zone $CLUSTER_ZONE

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy
      