version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/python:3.8
    
    environment:
      GCLOUD_PROJECT_ID: 'cinema'  
      GCLOUD_SERVICE_ACCOUT: cinema-gke-deploy@cinema-389321.iam.gserviceaccount.com

    steps:
      - checkout

      # 安装 gcloud SDK
      - run:
          name: Install gcloud SDK
          command: |
            curl https://sdk.cloud.google.com > install.sh
            bash install.sh --disable-prompts
            source '/home/circleci/google-cloud-sdk/completion.bash.inc'
            source '/home/circleci/google-cloud-sdk/path.bash.inc'
            gcloud version
          # persist_to_workspace:
          #   root: .
          #   paths:
          #     - $BASH_ENV
            
      # 配置 gcloud SDK
      - run:
          name: Configure gcloud SDK
          command: |
            source '/home/circleci/google-cloud-sdk/completion.bash.inc'
            source '/home/circleci/google-cloud-sdk/path.bash.inc'
            gcloud auth activate-service-account --key-file=.circleci/service-account-key.json
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud container clusters create cinema_cluster --zone us-central1-a
            

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy
      