version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/python:3.8

    environment:
      GCLOUD_PROJECT_ID: cinema-389321  
      GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY

    steps:
      - checkout

      # 安装 gcloud SDK
      - run:
          name: Install gcloud SDK
          command: |
            curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --output google-cloud-sdk.tar.gz
            tar xf google-cloud-sdk.tar.gz
            ./google-cloud-sdk/install.sh --quiet
            echo 'export PATH="/home/circleci/project/google-cloud-sdk/path.bash.inc"' >> $BASH_ENV
          persist_to_workspace:
            root: .
            paths:
              - $BASH_ENV
      
      # 验证 gcloud 安装
      - run:
          name: Verify gcloud installation
          command: |
            echo $PATH
            gcloud version
            

      # # 配置 gcloud SDK
      # - run:
      #     name: Configure gcloud SDK
      #     command: |
      #       source $BASH_ENV
      #       echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      #       gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      #       gcloud config set project $GCLOUD_PROJECT_ID
            

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy
      