---

version: 2.1

jobs:
  build:
    - description: Install npm
    - machine: 
        truversion: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/python:3.8

    environment:
      GCLOUD_PROJECT_ID:  cinima-389321 
      GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY

    steps:
      - checkout

      - run:
          name: Install gcloud SDK
          command: |
            wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-365.0.0-linux-x86_64.tar.gz
            tar xf google-cloud-sdk-365.0.0-linux-x86_64.tar.gz
            ./google-cloud-sdk/install.sh
            source $HOME/google-cloud-sdk/path.bash.inc

     
    steps:
      - checkout
      # Install node
      - node/install
      # Install npm
      - node/install-npm
      # Download and cache dependencies
      - node/with-cache:
          steps:
            - run:
                name: Install application dependencies
                command: npm install
          # Save cache
          cache-key: package.json
          # Ignore non-checksum cache hits
          use-strict-cache: true
  
workflows:
  build_update_deploy:
    jobs:
      - build
      